import { bayer } from '../grid';
import type { Grid } from '../grid';

const E = '................';

/** Item icons, 16x16. */
// prettier-ignore
export const ITEM_SPRITES: Record<string, Grid> = {
  backpack: [
    E,
    '.....kkkkkk.....',
    '....kBkkkkbk....',
    '....kBk..kbk....',
    '..kkkkkkkkkkkk..',
    '.kBBBBBBBBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kbbbbbyybbbbbk.',
    '.kBBBBByyBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kBBbbbbbbbbBbk.',
    '.kBBbBBBBBBbBbk.',
    '.kBBbbbbbbbbBbk.',
    '.kbbbbbbbbbbbbk.',
    '..kkkkkkkkkkkk..',
    E,
  ],
  scroll_file: [
    E,
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kggggggggggggk.',
    '..kwwwwwwwwwgk..',
    '..kwddddddwwgk..',
    '..kwwwwwwwwwgk..',
    '..kwdddddwwwgk..',
    '..kwwwwwwwwwgk..',
    '..kwddddddwwgk..',
    '..kwwwwwwwwwgk..',
    '.kkwwwwwwwwwgkk.',
    '.kwwwwwwwwwwwwk.',
    '.kggggggggggggk.',
    '..kkkkkkkkkkkk..',
    E,
  ],
  magnifier_search: [
    E,
    '....kkkkk.......',
    '...kgggggk......',
    '..kgwwuuugk.....',
    '..kgwuuuugk.....',
    '..kguuuuugk.....',
    '..kguuuuUdk.....',
    '..kguuuUUdk.....',
    '...kgdddddkk....',
    '....kkkkkBbk....',
    '.........kBbk...',
    '..........kBbk..',
    '...........kBbk.',
    '............kkk.',
    E,
    E,
  ],
  terminal_bash: [
    E,
    E,
    '.kkkkkkkkkkkkkk.',
    '.kdrdydGddddddk.',
    '.kkkkkkkkkkkkkk.',
    '.kUUUUUUUUUUUUk.',
    '.kUGUUUUUUUUUUk.',
    '.kUUGUwwwwUUUUk.',
    '.kUGUUUUUUUUUUk.',
    '.kUUUUUUUUUUUUk.',
    '.kUwwUUUUUUUUUk.',
    '.kUUUUUUUUUUUUk.',
    '.kkkkkkkkkkkkkk.',
    E,
    E,
    E,
  ],
  globe_web: [
    E,
    '.....kkkkkk.....',
    '...kkuuGGuukk...',
    '..kwuGGGGuuuuk..',
    '..kuGGGDuuuuUk..',
    '.kwuuGDuuuGGuUk.',
    '.kuuuuGuuGGGDUk.',
    '.kuuuuuuuGGDDUk.',
    '.kuGGuuuuuGDuUk.',
    '.kuGGGuuuuuuUUk.',
    '..kuGDuuuuuUUk..',
    '..kuuuuuuuUUUk..',
    '...kkUUUUUUkk...',
    '.....kkkkkk.....',
    E,
    E,
  ],
  gear_mcp: [
    '......kkkk......',
    '.....kwwwgk.....',
    '...kkkwggdkkk...',
    '..kwwkwggdkwgk..',
    '..kwggggggggdk..',
    '.kkkwgdddgggdkk.',
    'kwwwgddkkgggggdk',
    'kwgggdk..kggggdk',
    'kwgggdk..kggggdk',
    'kggggggkkgggdddk',
    '.kkkgggggggdkkk.',
    '..kggggggggddk..',
    '..kggkgggdkgdk..',
    '...kkkgggdkkk...',
    '.....kddddk.....',
    '......kkkk......',
  ],
  star_pin: [
    E,
    '.......kk.......',
    '......kwyk......',
    '......kwyk......',
    '.....kwyyok.....',
    'kkkkkkyyyyokkkkk',
    '.kwyyyyyyyyyyok.',
    '..kyyyyyyyyyok..',
    '...kyyyyyyyok...',
    '....kyyyyyyk....',
    '...kyyyyyyyok...',
    '...kyyokkyyok...',
    '..kyyok..kyyok..',
    '..kkkk....kkkk..',
    E,
    E,
  ],
  letter_subagent: [
    E,
    E,
    E,
    '.kkkkkkkkkkkkkk.',
    '.kdwwwwwwwwwwdk.',
    '.kwdwwwwwwwwdwk.',
    '.kwwdwwwwwwdwwk.',
    '.kwwwdwwwwdwwwk.',
    '.kwwwwdrrdwwwwk.',
    '.kwwwwwrrwwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kggggggggggggk.',
    '.kkkkkkkkkkkkkk.',
    E,
    E,
    E,
  ],
  hammer_edit: [
    E,
    E,
    '...kkkkkkkkk....',
    '..kgwwwwgggkkk..',
    '..kgggggggggggk.',
    '..kddddddddkkggk',
    '...kkkkBbkk..kgk',
    '......kBbk....kk',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kbbk......',
    '......kkkk......',
    E,
  ],
  speech_prompt: [
    E,
    E,
    '..kkkkkkkkkkkk..',
    '.kwwwwwwwwwwwwk.',
    '.kwUwwwwwwwwwgk.',
    '.kwwUwddddddwgk.',
    '.kwUwwwwwwwwwgk.',
    '.kwwwwwwwwwwwgk.',
    '.kwwddddddddwgk.',
    '.kggggggggggggk.',
    '..kkwgkkkkkkkk..',
    '...kwgk.........',
    '...kgk..........',
    '...kk...........',
    E,
    E,
  ],
  map_instructions: [
    E,
    E,
    '.kkkkkkkkkkkkkk.',
    '.kGGGsBsssBrsrk.',
    '.kGGDsBsssBsrsk.',
    '.kGDssBsssBrsrk.',
    '.kssssBsssrsssk.',
    '.kssssBsssBsssk.',
    '.kssssBsrsBsssk.',
    '.kssssBsssBsuuk.',
    '.kssssrsssBuuUk.',
    '.kssssBsssBuUUk.',
    '.kssrsBsssBsUUk.',
    '.kkkkkkkkkkkkkk.',
    E,
    E,
  ],
  bundle_other: [
    E,
    '.....kk..kk.....',
    '....kuUkkUuk....',
    '.....kUUUUk.....',
    '......kyyk......',
    '....kkuuuUkk....',
    '...kuwuuuuUUk...',
    '..kuwuuuuuuUUk..',
    '..kuuuuuuuuuUk..',
    '.kuuuuuuuuuuUUk.',
    '.kuuuuuuuuuUUUk.',
    '.kUuuuuuuuUUUUk.',
    '..kUUUUUUUUUUk..',
    '...kkkkkkkkkk...',
    E,
    E,
  ],
  field_notes: [
    E,
    '..kkkkkkkkkkk...',
    '..kDGGGGGGGGGk..',
    '..kDGGGGGGGGGwk.',
    '..kDGkkkkkkGGwk.',
    '..kDGkwwwwkGGwk.',
    '..kDGkwddwkGGwk.',
    '..kDGkkkkkkGGwk.',
    '..kDGGGGGGGGGwk.',
    '..kDGGGGGGGGGwk.',
    '..kDGGGGGGGGGwk.',
    '..kDDDDDDDDDDwk.',
    '..kkkkkkrkkkkkk.',
    '.......krk......',
    '.......kkk......',
    E,
  ],
  pack_open: [
    E,
    E,
    '...kkkkkkkkkk...',
    '...kBbbbbbbbk...',
    '...kbbbyybbbk...',
    '..kkkkkkkkkkkk..',
    '.khhhhhhhhhhhhk.',
    '.kBhhhhhhhhhhbk.',
    '.kBBBBBBBBBBBbk.',
    '.kBBBBBBBBBBBbk.',
    '.kBkkkkkkkkkkbk.',
    '.kBkBBBBBBBbkbk.',
    '.kBkbbbbbbbbkbk.',
    '.kbkkkkkkkkkkbk.',
    '..kkkkkkkkkkkk..',
    E,
  ],
};

/** 8x8 versions of the item icons, for items flying and piling up in the 320x180 scene. */
// prettier-ignore
export const MINI_ICON_SPRITES: Record<string, Grid> = {
  mini_scroll_file: [
    'kkkkkkkk',
    'kwwwwwgk',
    '.kwddwk.',
    '.kwwwwk.',
    '.kwddwk.',
    '.kwwwwk.',
    'kwwwwwgk',
    'kkkkkkkk',
  ],
  mini_magnifier_search: [
    '.kkkk...',
    'kwwuuk..',
    'kwuuUk..',
    'kuuUUk..',
    '.kkkkBk.',
    '....kBk.',
    '.....kBk',
    '......kk',
  ],
  mini_terminal_bash: [
    'kkkkkkkk',
    'kddddddk',
    'kkkkkkkk',
    'kUUUUUUk',
    'kUGUUUUk',
    'kUUGUUUk',
    'kUGUwwUk',
    'kkkkkkkk',
  ],
  mini_globe_web: [
    '..kkkk..',
    '.kuGGuk.',
    'kwGGuuUk',
    'kuuGuGDk',
    'kuuuuGUk',
    'kGuuuuUk',
    '.kuuUUk.',
    '..kkkk..',
  ],
  mini_gear_mcp: [
    '...kk...',
    '.kkwgkk.',
    'kwwgggdk',
    '.kwkkgk.',
    '.kgkkdk.',
    'kggggddk',
    '.kkgdkk.',
    '...kk...',
  ],
  mini_letter_subagent: [
    '........',
    'kkkkkkkk',
    'kkwwwwkk',
    'kwkwwkwk',
    'kwwrrwwk',
    'kwwwwwgk',
    'kkkkkkkk',
    '........',
  ],
  mini_hammer_edit: [
    'kkkkkk..',
    'kgwggkk.',
    'kddddggk',
    '.kkbkkk.',
    '..kbk...',
    '..kbk...',
    '..kbk...',
    '..kkk...',
  ],
  mini_speech_prompt: [
    '........',
    '.kkkkkk.',
    'kwwwwwwk',
    'kwUwddwk',
    'kwwwwwwk',
    '.kwkkkk.',
    '.kk.....',
    '........',
  ],
  mini_map_instructions: [
    'kkkkkkkk',
    'kGGsBrsk',
    'kGssBsrk',
    'kssrBssk',
    'ksrsBuuk',
    'krssBuUk',
    'kkkkkkkk',
    '........',
  ],
  mini_bundle_other: [
    '...kk...',
    '..kyyk..',
    '.kkuukk.',
    'kuwuuuUk',
    'kwuuuuUk',
    'kuuuuUUk',
    '.kUUUUk.',
    '..kkkk..',
  ],
  mini_star_pin: [
    '...kk...',
    '..kwyk..',
    'kkkyyokk',
    'kyyyyyok',
    '.kyyyok.',
    '.kyyyyk.',
    'kyokkyok',
    'kkk..kkk',
  ],
  mini_field_notes: [
    'kkkkkkk.',
    'kDGGGGkk',
    'kDwwwGwk',
    'kDGGGGwk',
    'kDGGGGwk',
    'kDDDDDwk',
    'kkkrkkkk',
    '...k....',
  ],
};

/** The campfire item icon, 16x16. Its flames may edge in fire red instead of outline. */
// prettier-ignore
export const CAMPFIRE_ICON: Grid = [
  E,
  '.......r........',
  '.......rr.......',
  '......ror.......',
  '......roor......',
  '.....rooor......',
  '.....royoor.....',
  '....rooyyor.....',
  '....royyyoor....',
  '...rooyyyyor....',
  '...royyyyyoor...',
  '.kk.royyyyor.kk.',
  'kBbkkroooorkkBbk',
  '.kkBbkkrrkkBbkk.',
  '...kkBbkkBbkk...',
  '.....kkkkkk.....',
];

/** Small flying letter, 8x6, carried from a returning companion to the hiker. */
// prettier-ignore
export const LETTER_MINI: Grid = [
  'kkkkkkkk',
  'kkwwwwkk',
  'kwkwwkwk',
  'kwwrrwwk',
  'kwwwwwgk',
  'kkkkkkkk',
];

/** A 1 px gold ring drawn over a 16x16 slot. */
// prettier-ignore
export const PIN_GLOW: Grid = [
  '..yyyyyyyyyyyy..',
  '.y............y.',
  'y..............y',
  ...Array.from({ length: 10 }, () => 'y..............y'),
  'y..............y',
  '.y............y.',
  '..yyyyyyyyyyyy..',
];

/**
 * A washed-out fade over a 16x16 icon. Paper pixels in an ordered dither that thickens
 * toward the bottom, so a stale item reads as sun-bleached rather than hidden.
 */
export const STALE_OVERLAY: Grid = ditherFade(16, 16, 'w');

function ditherFade(width: number, height: number, key: string): string[] {
  return Array.from({ length: height }, (_, r) => {
    const level = 5 + Math.round((r / (height - 1)) * 5);
    return Array.from({ length: width }, (_cell, c) => (bayer(c, r) < level ? key : '.')).join('');
  });
}

/** The gold ring sized for an 8x8 mini icon, 10x10. */
// prettier-ignore
export const MINI_PIN_GLOW: Grid = [
  '..yyyyyy..',
  '.y......y.',
  ...Array.from({ length: 6 }, () => 'y........y'),
  '.y......y.',
  '..yyyyyy..',
];
