import { textGrid } from '../font';
import { gridWidth, stamp } from '../grid';
import type { Grid } from '../grid';

const E = '................';

/** Seamless trail and grass tiles, 16x16. Grass edges in dark green, not outline black. */
// prettier-ignore
export const TERRAIN_SPRITES: Record<string, Grid> = {
  ground_dirt: [
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBbbBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBsBBBB',
    'BBBBBBBBBBsbBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BsBBBBBBBBBBBBBB',
    'BbBBBBBBBBBBbbBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
  ],
  ground_dirt_rut: [
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBbbbbbBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBsBB',
    'BBBBBBBBBBBBsbBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBbbbbbbBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
    'BBBBBBBBBBBBBBBB',
  ],
  ground_grass: [
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGDGDGGGG',
    'GGGGGGGGGGDGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGDGDGGGGGGGGGGG',
    'GGGDGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGDGD',
    'GGGGGGGGGGGGGGDG',
    'GGGGGGGGGGGGGGGG',
  ],
  ground_grass_edge: [
    '................',
    '................',
    '..........D.....',
    '..D......DlD....',
    '.DlD..D..DGD..D.',
    'DGlGDDlDDGGGDDlD',
    'GlGGGlGGGGlGGlGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'DGDDDGDDDDDGDDDD',
    'bDbbbDbbBbbDbbbb',
    'BbBBBbBBBBBbBBBB',
    'BBBBBBBBBBBBBBBB',
  ],
  ground_grass_front: [
    '................',
    '................',
    '.....D..........',
    '....DlD.....D...',
    '.D..DGD..D.DlD..',
    'DlDDGlGDDlDDGGDD',
    'lGGlGGGlGGGlGGlG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGDGDGGGGGGG',
    'GGGGGGGDGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GGGGGGGGGGGGGGGG',
    'GDGDGGGGGGGGGGGG',
    'GGDGGGGGGGGGGGGG',
  ],
};

/** Trees, 16x32, two tiles tall so they stand above the hiker. Lit from the top left. */
// prettier-ignore
export const TREE_SPRITES: Record<string, Grid> = {
  tree_pine: [
    E,
    E,
    '.......kk.......',
    '......klDk......',
    '......klDk......',
    '.....klGDDk.....',
    '.....kGDDDk.....',
    '....klGDDDDk....',
    '....kGDDDDDk....',
    '...klGDDDDDDk...',
    '...kkkDDDDkkk...',
    '....klGDDDDk....',
    '...klGDDDDDDk...',
    '...kGDDDDDDDk...',
    '..klGDDDDDDDDk..',
    '..kGDDDDDDDDDk..',
    '..kkkDDDDDDkkk..',
    '...klGDDDDDDk...',
    '..klGDDDDDDDDk..',
    '.klGDDDDDDDDDDk.',
    '.kGDDDDDDDDDDDk.',
    'klGDDDDDDDDDDDDk',
    'kGDDDDDDDDDDDDDk',
    'kkkkkkkbbkkkkkkk',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '.....kBBbbk.....',
    '.....kkkkkk.....',
  ],
  tree_round: [
    E,
    E,
    E,
    E,
    E,
    '......kkkk......',
    '...kkkllGGkkk...',
    '..kllGGGGGGGGk..',
    '.klGGGGGGGGGGGk.',
    '.klGGGGGGGGGGGk.',
    'klGGGGGGGGGGGGDk',
    'klGGGGlGGGGGGGDk',
    'kGGGGGDGGGGlGGDk',
    'kGGGGGGGGGGDGGDk',
    'kGGlGGGGGGGGGGDk',
    'kGGDGGGGGlGGGDDk',
    'kGGGGGGGGDGGGDDk',
    'kGGGGGGGGGGGGDDk',
    '.kGGGGlGGGGGDDk.',
    '.kGGGGDGGGGDDDk.',
    '.kDGGGGGGGDDDDk.',
    '..kDDGGGGDDDDk..',
    '...kkDDDDDDkk...',
    '.....kkbbkk.....',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '......kBbk......',
    '.....kBBbbk.....',
    '.....kkkkkk.....',
  ],
};

/** Props on the trail side, 16x16, standing on the bottom row. */
// prettier-ignore
export const PROP_SPRITES: Record<string, Grid> = {
  rock: [
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    '......kkkk......',
    '....kkwwggkk....',
    '...kwwgggggdk...',
    '..kwggggggggdk..',
    '..kwgggdggggdk..',
    '.kggggdggggdddk.',
    '.kkkkkkkkkkkkkk.',
  ],
  bush: [
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    '....kkkk........',
    '..kkllGGk.kkk...',
    '.kllGGGGGkllGk..',
    '.klGGrGGGGGGGDk.',
    'klGGGGGGGGrGGDDk',
    'kGGGrGGGGGGGGGDk',
    'kGGGGGGGGGGGrDDk',
    '.kDDGGGGGGGDDDk.',
    '..kkkkkkkkkkkk..',
  ],
  stump: [
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    '.....kkkkkk.....',
    '....kssssssk....',
    '....ksBBBBsk....',
    '....kbssssbk....',
    '....kBBBBbbk....',
    '....kBbBBbbk....',
    '...kBBbBBBbbk...',
    '...kkkkkkkkkk...',
  ],
  flowers: [
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    E,
    '...k.......k....',
    '..kwk.....kyk...',
    '.kwywk...kyoyk..',
    '..kwkkkkkkkykk..',
    '.klGGGlGGGGGlGk.',
    'klGGGGGGpGGGGGDk',
    'kGGGGGGGGGGGGDDk',
    '.kkkkkkkkkkkkkk.',
  ],
  signpost: [
    E,
    E,
    E,
    '.kkkkkkkkkkk....',
    '.kBBBBBBBBBBk...',
    '.kBbbBbbbBBBBk..',
    '.kBBBBBBBBBBBBk.',
    '.kbbbbbbbbbbbk..',
    '.kkkkkBbkkkkk...',
    '.....kBbk.......',
    '.....kBbk.......',
    '.....kBbk.......',
    '.....kBbk.......',
    '.....kBbk.......',
    '.....kBbk.......',
    '.....kkkk.......',
  ],
  lost_and_found_chest: [
    E,
    E,
    E,
    '...kkkkkkkkkk...',
    '..kBBgBBBBgBBk..',
    '.kBBBgBBBBgBBbk.',
    '.kbbbgbbbbgbbbk.',
    '.kkkkkkyykkkkkk.',
    '.kBBBgkyykgBBbk.',
    '.kBBBgBkkBgBBbk.',
    '.kBBBgBBBBgBBbk.',
    '.kbbbgbbbbgbbbk.',
    '.kkkkkkkkkkkkkk.',
    E,
    E,
    E,
  ],
};

const FIRE_LOGS = [
  '.kk.royyyyor.kk.',
  'kBbkkroooorkkBbk',
  '.kkBbkkrrkkBbkk.',
  '...kkBbkkBbkk...',
  '.....kkkkkk.....',
];

/** Flame frames, 16x16. Flames are edged in fire red instead of the dark outline. */
// prettier-ignore
export const CAMPFIRE_SPRITES: Record<string, Grid> = {
  campfire_1: [
    E,
    '.......r........',
    '.......rr.......',
    '......ror.......',
    '......roor......',
    '.....rooor...r..',
    '.....royoor.....',
    '....rooyyor.....',
    '....royyyoor....',
    '...rooyyyyor....',
    '...royyyyyoor...',
    ...FIRE_LOGS,
  ],
  campfire_2: [
    E,
    '......r.........',
    '......rr........',
    '..r...ror.......',
    '.....roor.......',
    '.....royor......',
    '....rooyor......',
    '....royyoor.....',
    '...rooyyyor.....',
    '...royyyyoor....',
    '...royyyyyyor...',
    ...FIRE_LOGS,
  ],
  campfire_3: [
    '.........r......',
    '........rr......',
    '...r....ror.....',
    '...rr..roor.....',
    '...ror.royr.....',
    '....rorroyor....',
    '....rooooyor....',
    '....royyyyor....',
    '...rooyywyoor...',
    '...royyyyyyor...',
    '...rooyyyyyor...',
    ...FIRE_LOGS,
  ],
};

const SIGN_WIDTH = 24;
const SIGN_HEIGHT = 24;
const BOARD_HEIGHT = 15;

/**
 * A trail sign, 24x24. Two lines of 3x5 text on a board over a post. Wider than a tile
 * because "AHEAD" needs 19 pixels. The board is shaded along its bottom and right edges.
 */
function trailSignGrid(
  lines: readonly [string, string],
  board: string,
  shade: string,
  ink: string,
): string[] {
  const edge = `.${'k'.repeat(SIGN_WIDTH - 2)}.`;
  const bevel = `k${shade.repeat(SIGN_WIDTH - 2)}k`;
  const face = `k${board.repeat(SIGN_WIDTH - 3)}${shade}k`;
  const boardRows = [edge, ...Array.from({ length: BOARD_HEIGHT - 3 }, () => face), bevel, edge];
  const post = '..........kBbk..........';
  const sign = [
    ...boardRows,
    ...Array.from({ length: SIGN_HEIGHT - BOARD_HEIGHT - 1 }, () => post),
    '..........kkkk..........',
  ];
  return lines.reduce<string[]>((grid, line, i) => {
    const text = textGrid(line, ink);
    const x = Math.floor((SIGN_WIDTH - gridWidth(text)) / 2);
    return stamp(grid, text, x, 2 + i * 6);
  }, sign);
}

export const SIGN_SPRITES: Record<string, Grid> = {
  trail_sign_60: trailSignGrid(['CAMP', 'AHEAD'], 'B', 'b', 'k'),
  trail_sign_75: trailSignGrid(['CAMP', 'SOON'], 'y', 'o', 'k'),
  trail_sign_90: trailSignGrid(['CAMP', 'NOW!'], 'r', 'b', 'w'),
};
